name: CI/CD Pipeline

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

jobs:
 # User Service Job
 user-service:
   name: 🐳 User Service - Build and Push Docker Image
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Node.js for User Service
       uses: actions/setup-node@v3
       with:
         node-version: '20'

     - name: Install dependencies for User Service
       run: npm install
       working-directory: ./user-service

     - name: Build Docker image for User Service
       run: docker build -t user-service ./user-service

 # Video Service Job
 video-service:
   name: 🎥 Video Service - Build and Push Docker Image
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Node.js for Video Service
       uses: actions/setup-node@v3
       with:
         node-version: '20'

     - name: Install dependencies for Video Service
       run: npm install
       working-directory: ./video-service

     - name: Build Docker image for Video Service
       run: docker build -t video-service ./video-service

 # API Gateway Job
 api-gateway:
   name: 🚪 API Gateway - Build and Push Docker Image
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Node.js for API Gateway
       uses: actions/setup-node@v3
       with:
         node-version: '20'

     - name: Install dependencies for API Gateway
       run: npm install
       working-directory: ./api-gateway

     - name: Build Docker image for API Gateway
       run: docker build -t api-gateway ./api-gateway

 # Frontend Service Job
 frontend:
   name: 💻 Frontend - Build and Push Docker Image
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Node.js for Frontend
       uses: actions/setup-node@v3
       with:
         node-version: '20'

     - name: Install dependencies for Frontend
       run: npm install
       working-directory: ./frontend

     - name: Build Docker image for Frontend
       run: docker build -t frontend ./frontend
